# Generated by Django 3.1.1 on 2020-10-11 03:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('age', models.IntegerField()),
                ('kitNumber', models.IntegerField(verbose_name='Kit Number')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FW', 'Forward')], default='GK', max_length=3)),
                ('preferredFoot', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('B', 'Both')], default='R', max_length=1, verbose_name='Preferred Foot')),
            ],
            options={
                'ordering': ['kitNumber'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill', models.CharField(choices=[('SQD', 'Team'), ('GK', 'Goalkeeping'), ('DEF', 'Defending'), ('PAS', 'Passing'), ('STR', 'Strength'), ('FIT', 'Fitness'), ('SHO', 'Shooting')], default='SQD', max_length=3)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('duration', models.IntegerField(verbose_name='Duration (minutes)')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('clean_sheets', models.IntegerField(blank=True, null=True)),
                ('shots', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Appearance Date')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='training',
            field=models.ManyToManyField(blank=True, to='main_app.Training'),
        ),
    ]
